---
abstract: 'tests to check your code against best practices'
author:
  - 'Jerome Quelin'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092200'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CriticTests
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  English: 0
  File::Find::Rule: 0
  Moose: 0
  Test::More: 0
resources:
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-CriticTests
  repository: http://github.com/jquelin/dist-zilla-plugin-critictests
version: 0.1.0
