---
abstract: 'tests to check your code against best practices'
author:
  - 'Jerome Quelin'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CriticTests
provides:
  Dist::Zilla::Plugin::CriticTests:
    file: lib/Dist/Zilla/Plugin/CriticTests.pm
    version: 1.102280
requires:
  Data::Section: 0.004
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::TextTemplate: 0
  Moose: 0
  Moose::Util: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-CriticTests
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-CriticTests/
  repository: http://github.com/jquelin/dist-zilla-plugin-critictests
version: 1.102280
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.101800
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@JQUELIN/CriticTests'
      version: 1.100140
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@JQUELIN/MetaTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@JQUELIN/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@JQUELIN/ReportVersions'
      version: 1.101700
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@JQUELIN/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@JQUELIN/AutoPrereq'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@JQUELIN/PodWeaver'
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.101590
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.101490
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.11034304
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git/Check'
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git/Commit'
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/Git/Tag'
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git/Push'
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101900
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.101900
